services:
  - type: web
    name: agriprix
    runtime: java
    rootDir: agriprix-fix
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/agriprix-extremenord-1.0.0.jar
    envVars:
      envVars:
        - key: SPRING_PROFILES_ACTIVE
          value: production
databases:
  - name: agriprix-db
    databaseName: agriprix
    user: agriuser
    plan: free
